version: '3'
services:
  # web:
  #   build: .
  #   ports: 
  #     - "8080:8080"
  #   links:
  #     - redis
  redis:
    image: redis:alpine
    #command: ["redis-server", "--protected-mode", "no"]
    ports: 
      - "6379:6379"
    
